import asyncio
import os
import sys
import logging
from dotenv import load_dotenv
import httpx

load_dotenv()

# Force root logger to output to stdout
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("test_integration")

BASE_URL = os.getenv("BACKEND_URL", "http://localhost:8000")
TEST_EMAIL = "integration_test_user@example.com"
TEST_PASS = "TestPassword123!"

async def run_tests():
    logger.info("==================================================")
    logger.info("STARTING END-TO-END INTEGRATION TEST SUITE")
    logger.info("==================================================")

    from app.database import AsyncSessionLocal, Base, engine
    from app.models import User, JournalEntry, UserMemory, GrowthEvent, CompanionMessage
    from sqlalchemy import select

    # Clean up test user if existing
    async with AsyncSessionLocal() as session:
        user_res = await session.execute(select(User).filter(User.email == TEST_EMAIL))
        existing_user = user_res.scalars().first()
        if existing_user:
            logger.info(f"Cleaning up existing test user (ID: {existing_user.id})...")
            await session.delete(existing_user)
            await session.commit()

    # Import FastAPI app to run in-process or via AsyncClient
    from app.main import app
    from httpx import ASGITransport

    transport = ASGITransport(app=app)
    async with httpx.AsyncClient(transport=transport, base_url="http://test") as client:
        # 1. Register test user
        logger.info("\n1. Registering test user...")
        reg_res = await client.post("/api/auth/register", json={
            "email": TEST_EMAIL,
            "password": TEST_PASS,
            "name": "Alex Explorer",
        })
        assert reg_res.status_code == 200, f"Register failed: {reg_res.text}"
        auth_data = reg_res.json()
        token = auth_data["access_token"]
        headers = {"Authorization": f"Bearer {token}"}

        me_res = await client.get("/api/auth/me", headers=headers)
        assert me_res.status_code == 200, f"Get /me failed: {me_res.text}"
        user_info = me_res.json()
        logger.info(f"SUCCESS: Registered user '{user_info['name']}' (ID: {user_info['id']})")

        # 2. Check initial Tree status & Insights
        logger.info("\n2. Checking initial Life Tree & Insights...")
        tree_res = await client.get("/api/tree/status", headers=headers)
        assert tree_res.status_code == 200, f"Tree status failed: {tree_res.text}"
        initial_tree = tree_res.json()
        logger.info(f"Initial Tree: Stage='{initial_tree['stage']}', Points={initial_tree['points']}")

        insights_res = await client.get("/api/insights/summary", headers=headers)
        assert insights_res.status_code == 200, f"Insights failed: {insights_res.text}"
        initial_insights = insights_res.json()
        logger.info(f"Initial Insights: Reflections={initial_insights['total_reflections']}, Memories={initial_insights['total_memories']}")

        # 3. Create Journal Entry
        logger.info("\n3. Creating guided journal entry with memory & gratitude...")
        journal_payload = {
            "title": "Passed My Calculus Final Exam",
            "reflection": "I felt so relieved today! My sister Priya helped me study all week, and all that hard work paid off when I got an A grade.",
            "mood": "ecstatic",
            "emoji": "🎉",
            "highlight": "Getting an A in calculus after studying with my sister Priya.",
            "emotional_checkin": "Feeling proud and calm.",
            "lesson_learned": "Consistency and asking for help from family makes tough goals achievable.",
            "gratitude": "Grateful for sister Priya and my mentor Professor Davis.",
            "tomorrow_focus": "Start working on computer science project.",
            "memory_note": "Sister Priya always helps with math.",
            "is_pinned": True
        }
        entry_res = await client.post("/api/journal/entries", json=journal_payload, headers=headers)
        assert entry_res.status_code == 200, f"Create entry failed: {entry_res.text}"
        entry_data = entry_res.json()
        logger.info(f"SUCCESS: Created Journal Entry ID={entry_data['id']}")
        logger.info(f"AI Reflection generated by Groq LLM:\n  -> \"{entry_data.get('ai_reflection')}\"")

        # 4. Verify Memory extraction
        logger.info("\n4. Verifying automatic long-term memory extraction from Journal...")
        mem_res = await client.get("/api/memories/facts", headers=headers)
        assert mem_res.status_code == 200, f"List memories failed: {mem_res.text}"
        memories = mem_res.json()
        logger.info(f"Extracted {len(memories)} memory facts from journal entry:")
        for m in memories:
            logger.info(f"  - [{m['category']}] {m['key_name']}: {m['fact_value']} (Source: {m['source']})")
        assert len(memories) > 0, "ERROR: No memories extracted from journal entry!"

        # 5. Verify Life Tree growth
        logger.info("\n5. Verifying Life Tree points update...")
        tree_res2 = await client.get("/api/tree/status", headers=headers)
        tree_data2 = tree_res2.json()
        logger.info(f"Updated Tree: Stage='{tree_data2['stage']}', Points={tree_data2['points']} (was {initial_tree['points']})")
        assert tree_data2['points'] > initial_tree['points'], "ERROR: Life Tree points did not increase after journal entry!"

        # 6. Verify Insights recalculation
        logger.info("\n6. Verifying Insights analytics update...")
        insights_res2 = await client.get("/api/insights/summary", headers=headers)
        insights2 = insights_res2.json()
        logger.info(f"Updated Insights:")
        logger.info(f"  - Total Reflections: {insights2['total_reflections']}")
        logger.info(f"  - Total Memories: {insights2['total_memories']}")
        logger.info(f"  - Happiness %: {insights2['happiness_percentage']}%")
        logger.info(f"  - Top Moods: {insights2['top_moods']}")
        logger.info(f"  - Weekly Summary (LLM Narrative):\n    -> \"{insights2['weekly_summary']}\"")
        assert insights2['total_reflections'] == 1, "ERROR: Insights reflection count is wrong!"
        assert insights2['total_memories'] == len(memories), "ERROR: Insights memory count is wrong!"

        # 7. Water Life Tree
        logger.info("\n7. Water Life Tree...")
        water_res = await client.post("/api/tree/water", headers=headers)
        assert water_res.status_code == 200, f"Water tree failed: {water_res.text}"
        water_data = water_res.json()
        logger.info(f"Water Tree Response: {water_data['message']}")

        # 8. Test Nova AI Chatbot (reading Journal + Memory + Insights + Tree)
        logger.info("\n8. Testing Nova AI Chatbot with full context awareness...")
        chat_payload = {
            "message": "Hey Nova! Can you remind me who helped me with my exam and how my growth tree is doing?",
            "personality": "empowering coach"
        }
        chat_res = await client.post("/api/companion/chat", json=chat_payload, headers=headers)
        assert chat_res.status_code == 200, f"Chat failed: {chat_res.text}"
        chat_reply = chat_res.json()
        logger.info(f"Nova AI Assistant Response:\n  -> \"{chat_reply['content']}\"")
        assert len(chat_reply['content']) > 20, "ERROR: Chatbot returned short fallback message!"
        
        # Verify Nova mentions Priya or exam or calculus or growth tree
        reply_lower = chat_reply['content'].lower()
        has_context_reference = any(k in reply_lower for k in ["priya", "sister", "calculus", "exam", "tree", "sprout", "plant", "points", "growth"])
        logger.info(f"Context awareness verified (mentions memories/journal/tree): {has_context_reference}")
        assert has_context_reference, "ERROR: Chatbot response did not reference user memory context!"

        # 9. Test AI Memory Recall endpoint
        logger.info("\n9. Testing AI Memory Recall endpoint...")
        recall_res = await client.post("/api/memories/recall", json={"topic": "Academics & Family"}, headers=headers)
        assert recall_res.status_code == 200, f"Memory recall failed: {recall_res.text}"
        recall_data = recall_res.json()
        logger.info(f"AI Memory Recall Summary:\n  -> \"{recall_data['recall_summary']}\"")

        logger.info("\n==================================================")
        logger.info("ALL INTEGRATION TESTS PASSED SUCCESSFULLY!")
        logger.info("==================================================")

if __name__ == "__main__":
    asyncio.run(run_tests())
